# Generated by Django 4.0.2 on 2022-03-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_alter_doctor_date_of_birth_alter_doctor_email_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='patient_id',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='record_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='report',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_relation',
            field=models.CharField(choices=[('first degree', 'First Degree'), ('second degree', 'Second Degree')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/04d9adfe-78c1-4572-b667-1ee33eae4e8c'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorAppointment',
        ),
        migrations.DeleteModel(
            name='PatientAppointment',
        ),
    ]
