# Generated by Django 4.0.2 on 2022-02-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='record_number',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_relation',
            field=models.CharField(choices=[('first degree', 'First Degree'), ('second degree', 'Second Degree')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/be19d699-7db5-49cd-9dea-22fa5bd7132e'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_superuser',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/47b82c67-1c62-4d0a-a3e2-58756a748b29'),
        ),
        migrations.DeleteModel(
            name='DoctorAppointment',
        ),
        migrations.DeleteModel(
            name='PatientAppointment',
        ),
    ]
