# Generated by Django 4.0.2 on 2022-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_doctorappointment_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/78a1abe5-f879-42c1-99ef-5e7805ec8e78'),
        ),
    ]
