# Generated by Django 4.0.2 on 2022-02-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
        ('user', '0002_remove_patientappointment_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/5fc3aa04-1812-48df-9760-3f20be52028d'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
