# Generated by Django 4.0.2 on 2022-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appointment_doctor_id_alter_comment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e413d63c-21e5-451f-be85-1ca44b7218ab'),
        ),
    ]
