# Generated by Django 4.0.2 on 2022-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_alter_doctor_image'),
        ('user', '0003_alter_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='doctor_ids',
            field=models.ManyToManyField(null=True, to='Doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/ea02c67d-afab-4be1-a5bf-985314042343'),
        ),
    ]
