# Generated by Django 4.0.2 on 2022-02-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/2449f688-2bd9-45fe-891e-e5090450ff57'),
        ),
    ]
