# Generated by Django 4.0.2 on 2022-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_doctor_id_customuser_doctor_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/c4046cbb-6078-458e-9fca-2f6d066cf370'),
        ),
    ]
