# Generated by Django 4.0.2 on 2022-02-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_fullname_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/084a06c5-336f-4cad-98cb-ceaf7ea0a994'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/12751de5-8c3d-4ef0-b04c-5df235691133'),
        ),
    ]
