# Generated by Django 4.0.2 on 2022-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_options_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/aa6340c5-29e9-48e1-bad4-f602d5e0555d'),
        ),
    ]
