# Generated by Django 4.0.2 on 2022-02-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/40b1a8d1-8fdb-4936-bf85-61d72ad9964d'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/f634344a-f373-4ae9-9508-d0d9899f07d5'),
        ),
    ]
