# Generated by Django 4.0.2 on 2022-02-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/21508747-bb33-49eb-a44d-1558cd9a1c40'),
        ),
    ]
