# Generated by Django 4.0.2 on 2022-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0007_alter_doctor_image'),
        ('user', '0006_alter_customuser_doctor_ids_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='doctor_ids',
            field=models.ManyToManyField(null=True, to='Doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/876302e1-1da2-40e5-8f5f-fca2dc71a437'),
        ),
    ]
