# Generated by Django 4.0.2 on 2022-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_doctor_ids_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/0dbea422-70c4-4ef9-872a-f625752b20c0'),
        ),
    ]
