# Generated by Django 4.0.2 on 2022-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/47846270-bc86-476e-b196-54ebe3b142af'),
        ),
    ]
