# Generated by Django 4.0.2 on 2022-02-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/101225ec-1bf5-463f-a04a-8b2dd27069f6'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/db1c46da-bc6e-4ec5-8341-18a66eb50d8a'),
        ),
    ]
