# Generated by Django 4.0.2 on 2022-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='doctor_ids',
            new_name='doctors',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/33431d30-c1c5-40fc-a180-a5d0183ceb8e'),
        ),
    ]
