# Generated by Django 4.0.2 on 2022-02-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/a34649b5-f357-4548-b704-73a800d48d78'),
        ),
    ]
