# Generated by Django 4.0.2 on 2022-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_managers_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/8ea1b5cc-0690-4a5d-87a7-741a41480cc2'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/b1c5db84-9d45-44a9-8792-5bb6bd988129'),
        ),
    ]
