# Generated by Django 4.0.2 on 2022-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0010_alter_doctor_image'),
        ('user', '0009_rename_doctor_ids_customuser_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='doctors',
            field=models.ManyToManyField(to='Doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/8a347684-d4a2-4600-b3bb-333f3ae0793a'),
        ),
    ]
