# Generated by Django 4.0.2 on 2022-02-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/16ad7893-3c30-4b21-b78f-7143ffc687aa'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/9fc953dc-45d0-4dfc-9d35-fe9421b1223f'),
        ),
    ]
