# Generated by Django 4.0.2 on 2022-02-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/d2c22bd7-b22d-4df9-8a54-64046e3cc139'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e8ea8afd-e943-4833-a234-2700ab9757d4'),
        ),
    ]
