# Generated by Django 4.0.2 on 2022-02-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/281a4db5-d7a1-4dc7-b9b1-a4e5574ff3d5'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/d111c7e8-9647-424a-bfb2-dc88f5e7b139'),
        ),
    ]
