# Generated by Django 4.0.2 on 2022-02-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/4b88d8dc-6cfb-401c-96c9-0aa69b8aef4b'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/da984da3-7673-4d73-9d63-28c05e3b93b5'),
        ),
    ]
