# Generated by Django 4.0.2 on 2022-02-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/ecca7221-2981-4f72-a00a-b832770fc0ed'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/07cf1bf4-6f0c-4636-9a47-927c3dd5512e'),
        ),
    ]
