# Generated by Django 4.0.2 on 2022-02-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/4b802334-3ed1-4cfe-9498-67777b70b8c5'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/9bb4746a-67f9-425b-b73e-9c0532774754'),
        ),
    ]
