# Generated by Django 4.0.2 on 2022-02-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/f09cc375-7124-47a8-9595-0a18343599ac'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/0fc4ee6a-290b-4928-8566-bf57957e2802'),
        ),
    ]
