# Generated by Django 4.0.2 on 2022-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/3ef18a41-cdfd-46b0-8a80-e8f4c4b3c32d'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/99e9b4c8-4de1-40c5-a159-344b97538ede'),
        ),
    ]
