# Generated by Django 4.0.2 on 2022-02-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_customuser_fullname_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/615c9866-dbae-4220-98c0-44097155994f'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/41659806-3394-4125-a3eb-8c816f3a74aa'),
        ),
    ]
