# Generated by Django 4.0.2 on 2022-02-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/0959aff6-ac85-47d8-ab1c-b715e23b5008'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/918b3491-40cc-4beb-8ed1-53ddf70ae504'),
        ),
    ]
