# Generated by Django 4.0.2 on 2022-02-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/a248d784-9efb-45e1-8c49-1d3d35f110d2'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e49b2b81-6db0-4584-8e81-3f24cd4fcb5e'),
        ),
    ]
