# Generated by Django 4.0.2 on 2022-02-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/bcd60018-2329-40cb-b5db-20bb9541df3a'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/5dcc45a0-f33d-4074-a32f-0f9b21a5f463'),
        ),
    ]
