# Generated by Django 4.0.2 on 2022-02-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_comment_date_added_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/2dfed674-10c8-4448-b861-58e276c5c124'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/46a8025f-c247-4bc5-a92c-1a345695976b'),
        ),
    ]
