# Generated by Django 4.0.2 on 2022-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_customuser_fullname_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/41fa7b15-b1a8-4ebb-a451-d7386eb7ae7e'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/760762b9-09b8-4aa3-92d6-a6698bfc5bb7'),
        ),
    ]
