# Generated by Django 4.0.2 on 2022-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/94d95d33-5fae-43f8-a671-e5004455810f'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/ccb5eb8c-a9b3-4078-ae01-3c406ebb81ac'),
        ),
    ]
