# Generated by Django 4.0.2 on 2022-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='isdocor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/bc123e23-3b28-4dbf-9218-07a5ad459ba9'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/fd11b7c9-476a-4d45-a785-cd946cb67dac'),
        ),
    ]
