# Generated by Django 4.0.2 on 2022-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_doctor_isdocor_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='isdocor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='isdocor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/d50ba55c-e9d4-4560-9720-fb62ac432b6e'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/60879dc9-30d1-45c4-a953-e789da8ba364'),
        ),
    ]
