# Generated by Django 4.0.2 on 2022-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_remove_doctor_isdocor_customuser_isdocor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/497f59df-ae85-435a-b698-e61b86d5e1b9'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/df698c42-cf7b-4ff0-b792-f7f2ecbc6d68'),
        ),
    ]
