# Generated by Django 4.0.2 on 2022-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_customuser_image_alter_doctor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isdocor',
            new_name='isadmin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/5f5efeec-bc6c-486a-9f92-3ef172279895'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/21fe5b19-12e6-4394-b029-f68d990a663f'),
        ),
    ]
