# Generated by Django 4.0.2 on 2022-02-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_rename_isdocor_customuser_isadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guardian_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_relation',
            field=models.CharField(choices=[('first degree', 'First Degree'), ('second degree', 'Second Degree')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/c8b6a6ad-94cc-4862-ae58-52ab660445e8'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/1ce14642-65c2-43a5-b8b5-e51deb8a9f7f'),
        ),
    ]
