# Generated by Django 4.0.2 on 2022-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_customuser_guardian_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isadmin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/5553cd42-fba5-41bb-89a1-0e928cc0507e'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/962e38f5-1d1b-4c26-97e8-cded5c4e2281'),
        ),
    ]
