# Generated by Django 4.0.2 on 2022-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_remove_customuser_isadmin_alter_customuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='record_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/740f9ca6-d913-4f95-8322-cf51912f9253'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/1698555b-a942-4709-95a6-0ec7b81d91e4'),
        ),
    ]
