# Generated by Django 4.0.2 on 2022-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/6b5ecb9d-90f1-4c31-a92e-e725c453e9c8'),
        ),
    ]
