# Generated by Django 4.0.2 on 2022-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/8a4982fb-1d73-4985-9d6d-249c3e809c5b'),
        ),
    ]
