# Generated by Django 4.0.2 on 2022-02-28 08:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_remove_doctor_address_remove_doctor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/714ac8b9-7f97-4bfb-a627-367586fced9a'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='phone must be an egyptian phone number...', regex='^01[1|0|2|5][0-9]{8}$')], verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='none', max_length=50, unique=True),
        ),
    ]
