# Generated by Django 4.0.2 on 2022-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/b3739ab6-1ce4-493d-83ef-7adb29b0bd30'),
        ),
    ]
