# Generated by Django 4.0.2 on 2022-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0005_doctor_address_doctor_date_of_birth_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/60d3071b-7cb8-4c69-9a8f-aca3e95db150'),
        ),
    ]
