# Generated by Django 4.0.2 on 2022-02-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0006_doctor_password_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/4825fecc-c677-4efb-a129-d7d137a94649'),
        ),
    ]
