# Generated by Django 4.0.2 on 2022-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0007_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/972b6c98-5af2-4a91-9c46-a171de014401'),
        ),
    ]
