# Generated by Django 4.0.2 on 2022-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0009_alter_doctor_education_degree_alter_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/0bd9bd35-9c5a-4c58-8a9c-0266774ddedf'),
        ),
    ]
